//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppIndigo.ServiceReferenceProducto {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InsertPro", Namespace="http://schemas.datacontract.org/2004/07/Miguelwcf")]
    [System.SerializableAttribute()]
    public partial class InsertPro : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodigoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripcionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double PrecioventaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int StockmaximoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int StockminimoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Codigo {
            get {
                return this.CodigoField;
            }
            set {
                if ((object.ReferenceEquals(this.CodigoField, value) != true)) {
                    this.CodigoField = value;
                    this.RaisePropertyChanged("Codigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descripcion {
            get {
                return this.DescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionField, value) != true)) {
                    this.DescripcionField = value;
                    this.RaisePropertyChanged("Descripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Precioventa {
            get {
                return this.PrecioventaField;
            }
            set {
                if ((this.PrecioventaField.Equals(value) != true)) {
                    this.PrecioventaField = value;
                    this.RaisePropertyChanged("Precioventa");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Stockmaximo {
            get {
                return this.StockmaximoField;
            }
            set {
                if ((this.StockmaximoField.Equals(value) != true)) {
                    this.StockmaximoField = value;
                    this.RaisePropertyChanged("Stockmaximo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Stockminimo {
            get {
                return this.StockminimoField;
            }
            set {
                if ((this.StockminimoField.Equals(value) != true)) {
                    this.StockminimoField = value;
                    this.RaisePropertyChanged("Stockminimo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="getDatos", Namespace="http://schemas.datacontract.org/2004/07/Miguelwcf")]
    [System.SerializableAttribute()]
    public partial class getDatos : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Data.DataTable productoTabField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Data.DataTable productoTab {
            get {
                return this.productoTabField;
            }
            set {
                if ((object.ReferenceEquals(this.productoTabField, value) != true)) {
                    this.productoTabField = value;
                    this.RaisePropertyChanged("productoTab");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UpdateProducto", Namespace="http://schemas.datacontract.org/2004/07/Miguelwcf")]
    [System.SerializableAttribute()]
    public partial class UpdateProducto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodigoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripcionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double PrecioventaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int StockmaximoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int StockminimoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Codigo {
            get {
                return this.CodigoField;
            }
            set {
                if ((object.ReferenceEquals(this.CodigoField, value) != true)) {
                    this.CodigoField = value;
                    this.RaisePropertyChanged("Codigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descripcion {
            get {
                return this.DescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionField, value) != true)) {
                    this.DescripcionField = value;
                    this.RaisePropertyChanged("Descripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Precioventa {
            get {
                return this.PrecioventaField;
            }
            set {
                if ((this.PrecioventaField.Equals(value) != true)) {
                    this.PrecioventaField = value;
                    this.RaisePropertyChanged("Precioventa");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Stockmaximo {
            get {
                return this.StockmaximoField;
            }
            set {
                if ((this.StockmaximoField.Equals(value) != true)) {
                    this.StockmaximoField = value;
                    this.RaisePropertyChanged("Stockmaximo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Stockminimo {
            get {
                return this.StockminimoField;
            }
            set {
                if ((this.StockminimoField.Equals(value) != true)) {
                    this.StockminimoField = value;
                    this.RaisePropertyChanged("Stockminimo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DeleteProducto", Namespace="http://schemas.datacontract.org/2004/07/Miguelwcf")]
    [System.SerializableAttribute()]
    public partial class DeleteProducto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReferenceProducto.IProducto")]
    public interface IProducto {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProducto/Insert", ReplyAction="http://tempuri.org/IProducto/InsertResponse")]
        string Insert(WebAppIndigo.ServiceReferenceProducto.InsertPro Pro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProducto/Insert", ReplyAction="http://tempuri.org/IProducto/InsertResponse")]
        System.Threading.Tasks.Task<string> InsertAsync(WebAppIndigo.ServiceReferenceProducto.InsertPro Pro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProducto/getInfo", ReplyAction="http://tempuri.org/IProducto/getInfoResponse")]
        WebAppIndigo.ServiceReferenceProducto.getDatos getInfo();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProducto/getInfo", ReplyAction="http://tempuri.org/IProducto/getInfoResponse")]
        System.Threading.Tasks.Task<WebAppIndigo.ServiceReferenceProducto.getDatos> getInfoAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProducto/Update", ReplyAction="http://tempuri.org/IProducto/UpdateResponse")]
        string Update(WebAppIndigo.ServiceReferenceProducto.UpdateProducto Producto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProducto/Update", ReplyAction="http://tempuri.org/IProducto/UpdateResponse")]
        System.Threading.Tasks.Task<string> UpdateAsync(WebAppIndigo.ServiceReferenceProducto.UpdateProducto Producto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProducto/Delete", ReplyAction="http://tempuri.org/IProducto/DeleteResponse")]
        string Delete(WebAppIndigo.ServiceReferenceProducto.DeleteProducto Del);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProducto/Delete", ReplyAction="http://tempuri.org/IProducto/DeleteResponse")]
        System.Threading.Tasks.Task<string> DeleteAsync(WebAppIndigo.ServiceReferenceProducto.DeleteProducto Del);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IProductoChannel : WebAppIndigo.ServiceReferenceProducto.IProducto, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ProductoClient : System.ServiceModel.ClientBase<WebAppIndigo.ServiceReferenceProducto.IProducto>, WebAppIndigo.ServiceReferenceProducto.IProducto {
        
        public ProductoClient() {
        }
        
        public ProductoClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ProductoClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProductoClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProductoClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string Insert(WebAppIndigo.ServiceReferenceProducto.InsertPro Pro) {
            return base.Channel.Insert(Pro);
        }
        
        public System.Threading.Tasks.Task<string> InsertAsync(WebAppIndigo.ServiceReferenceProducto.InsertPro Pro) {
            return base.Channel.InsertAsync(Pro);
        }
        
        public WebAppIndigo.ServiceReferenceProducto.getDatos getInfo() {
            return base.Channel.getInfo();
        }
        
        public System.Threading.Tasks.Task<WebAppIndigo.ServiceReferenceProducto.getDatos> getInfoAsync() {
            return base.Channel.getInfoAsync();
        }
        
        public string Update(WebAppIndigo.ServiceReferenceProducto.UpdateProducto Producto) {
            return base.Channel.Update(Producto);
        }
        
        public System.Threading.Tasks.Task<string> UpdateAsync(WebAppIndigo.ServiceReferenceProducto.UpdateProducto Producto) {
            return base.Channel.UpdateAsync(Producto);
        }
        
        public string Delete(WebAppIndigo.ServiceReferenceProducto.DeleteProducto Del) {
            return base.Channel.Delete(Del);
        }
        
        public System.Threading.Tasks.Task<string> DeleteAsync(WebAppIndigo.ServiceReferenceProducto.DeleteProducto Del) {
            return base.Channel.DeleteAsync(Del);
        }
    }
}
