//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppIndigo.ServiceReferenceProveedor {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GuardaProve", Namespace="http://schemas.datacontract.org/2004/07/Miguelwcf")]
    [System.SerializableAttribute()]
    public partial class GuardaProve : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodigoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DireccionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TelefonoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Codigo {
            get {
                return this.CodigoField;
            }
            set {
                if ((object.ReferenceEquals(this.CodigoField, value) != true)) {
                    this.CodigoField = value;
                    this.RaisePropertyChanged("Codigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Direccion {
            get {
                return this.DireccionField;
            }
            set {
                if ((object.ReferenceEquals(this.DireccionField, value) != true)) {
                    this.DireccionField = value;
                    this.RaisePropertyChanged("Direccion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Telefono {
            get {
                return this.TelefonoField;
            }
            set {
                if ((object.ReferenceEquals(this.TelefonoField, value) != true)) {
                    this.TelefonoField = value;
                    this.RaisePropertyChanged("Telefono");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="getProveedores", Namespace="http://schemas.datacontract.org/2004/07/Miguelwcf")]
    [System.SerializableAttribute()]
    public partial class getProveedores : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Data.DataTable proveedorTabField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Data.DataTable proveedorTab {
            get {
                return this.proveedorTabField;
            }
            set {
                if ((object.ReferenceEquals(this.proveedorTabField, value) != true)) {
                    this.proveedorTabField = value;
                    this.RaisePropertyChanged("proveedorTab");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UpdateProve", Namespace="http://schemas.datacontract.org/2004/07/Miguelwcf")]
    [System.SerializableAttribute()]
    public partial class UpdateProve : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodigoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DireccionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TelefonoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Codigo {
            get {
                return this.CodigoField;
            }
            set {
                if ((object.ReferenceEquals(this.CodigoField, value) != true)) {
                    this.CodigoField = value;
                    this.RaisePropertyChanged("Codigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Direccion {
            get {
                return this.DireccionField;
            }
            set {
                if ((object.ReferenceEquals(this.DireccionField, value) != true)) {
                    this.DireccionField = value;
                    this.RaisePropertyChanged("Direccion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Telefono {
            get {
                return this.TelefonoField;
            }
            set {
                if ((object.ReferenceEquals(this.TelefonoField, value) != true)) {
                    this.TelefonoField = value;
                    this.RaisePropertyChanged("Telefono");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DeleteProveedor", Namespace="http://schemas.datacontract.org/2004/07/Miguelwcf")]
    [System.SerializableAttribute()]
    public partial class DeleteProveedor : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="getListProve", Namespace="http://schemas.datacontract.org/2004/07/Miguelwcf")]
    [System.SerializableAttribute()]
    public partial class getListProve : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Data.DataSet proveeTabField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Data.DataSet proveeTab {
            get {
                return this.proveeTabField;
            }
            set {
                if ((object.ReferenceEquals(this.proveeTabField, value) != true)) {
                    this.proveeTabField = value;
                    this.RaisePropertyChanged("proveeTab");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="getListAlma", Namespace="http://schemas.datacontract.org/2004/07/Miguelwcf")]
    [System.SerializableAttribute()]
    public partial class getListAlma : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Data.DataSet almaTabField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Data.DataSet almaTab {
            get {
                return this.almaTabField;
            }
            set {
                if ((object.ReferenceEquals(this.almaTabField, value) != true)) {
                    this.almaTabField = value;
                    this.RaisePropertyChanged("almaTab");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReferenceProveedor.IProveedor")]
    public interface IProveedor {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProveedor/Guardar", ReplyAction="http://tempuri.org/IProveedor/GuardarResponse")]
        string Guardar(WebAppIndigo.ServiceReferenceProveedor.GuardaProve Prove);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProveedor/Guardar", ReplyAction="http://tempuri.org/IProveedor/GuardarResponse")]
        System.Threading.Tasks.Task<string> GuardarAsync(WebAppIndigo.ServiceReferenceProveedor.GuardaProve Prove);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProveedor/getInfo", ReplyAction="http://tempuri.org/IProveedor/getInfoResponse")]
        WebAppIndigo.ServiceReferenceProveedor.getProveedores getInfo();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProveedor/getInfo", ReplyAction="http://tempuri.org/IProveedor/getInfoResponse")]
        System.Threading.Tasks.Task<WebAppIndigo.ServiceReferenceProveedor.getProveedores> getInfoAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProveedor/Update", ReplyAction="http://tempuri.org/IProveedor/UpdateResponse")]
        string Update(WebAppIndigo.ServiceReferenceProveedor.UpdateProve Prove);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProveedor/Update", ReplyAction="http://tempuri.org/IProveedor/UpdateResponse")]
        System.Threading.Tasks.Task<string> UpdateAsync(WebAppIndigo.ServiceReferenceProveedor.UpdateProve Prove);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProveedor/Delete", ReplyAction="http://tempuri.org/IProveedor/DeleteResponse")]
        string Delete(WebAppIndigo.ServiceReferenceProveedor.DeleteProveedor Prove);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProveedor/Delete", ReplyAction="http://tempuri.org/IProveedor/DeleteResponse")]
        System.Threading.Tasks.Task<string> DeleteAsync(WebAppIndigo.ServiceReferenceProveedor.DeleteProveedor Prove);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProveedor/getProveedores", ReplyAction="http://tempuri.org/IProveedor/getProveedoresResponse")]
        WebAppIndigo.ServiceReferenceProveedor.getListProve getProveedores();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProveedor/getProveedores", ReplyAction="http://tempuri.org/IProveedor/getProveedoresResponse")]
        System.Threading.Tasks.Task<WebAppIndigo.ServiceReferenceProveedor.getListProve> getProveedoresAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProveedor/getAlmacenes", ReplyAction="http://tempuri.org/IProveedor/getAlmacenesResponse")]
        WebAppIndigo.ServiceReferenceProveedor.getListAlma getAlmacenes();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProveedor/getAlmacenes", ReplyAction="http://tempuri.org/IProveedor/getAlmacenesResponse")]
        System.Threading.Tasks.Task<WebAppIndigo.ServiceReferenceProveedor.getListAlma> getAlmacenesAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IProveedorChannel : WebAppIndigo.ServiceReferenceProveedor.IProveedor, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ProveedorClient : System.ServiceModel.ClientBase<WebAppIndigo.ServiceReferenceProveedor.IProveedor>, WebAppIndigo.ServiceReferenceProveedor.IProveedor {
        
        public ProveedorClient() {
        }
        
        public ProveedorClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ProveedorClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProveedorClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProveedorClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string Guardar(WebAppIndigo.ServiceReferenceProveedor.GuardaProve Prove) {
            return base.Channel.Guardar(Prove);
        }
        
        public System.Threading.Tasks.Task<string> GuardarAsync(WebAppIndigo.ServiceReferenceProveedor.GuardaProve Prove) {
            return base.Channel.GuardarAsync(Prove);
        }
        
        public WebAppIndigo.ServiceReferenceProveedor.getProveedores getInfo() {
            return base.Channel.getInfo();
        }
        
        public System.Threading.Tasks.Task<WebAppIndigo.ServiceReferenceProveedor.getProveedores> getInfoAsync() {
            return base.Channel.getInfoAsync();
        }
        
        public string Update(WebAppIndigo.ServiceReferenceProveedor.UpdateProve Prove) {
            return base.Channel.Update(Prove);
        }
        
        public System.Threading.Tasks.Task<string> UpdateAsync(WebAppIndigo.ServiceReferenceProveedor.UpdateProve Prove) {
            return base.Channel.UpdateAsync(Prove);
        }
        
        public string Delete(WebAppIndigo.ServiceReferenceProveedor.DeleteProveedor Prove) {
            return base.Channel.Delete(Prove);
        }
        
        public System.Threading.Tasks.Task<string> DeleteAsync(WebAppIndigo.ServiceReferenceProveedor.DeleteProveedor Prove) {
            return base.Channel.DeleteAsync(Prove);
        }
        
        public WebAppIndigo.ServiceReferenceProveedor.getListProve getProveedores() {
            return base.Channel.getProveedores();
        }
        
        public System.Threading.Tasks.Task<WebAppIndigo.ServiceReferenceProveedor.getListProve> getProveedoresAsync() {
            return base.Channel.getProveedoresAsync();
        }
        
        public WebAppIndigo.ServiceReferenceProveedor.getListAlma getAlmacenes() {
            return base.Channel.getAlmacenes();
        }
        
        public System.Threading.Tasks.Task<WebAppIndigo.ServiceReferenceProveedor.getListAlma> getAlmacenesAsync() {
            return base.Channel.getAlmacenesAsync();
        }
    }
}
